#!/bin/bash

git config --global alias.d 'diff'
git config --global alias.dc 'diff --color-words'
git config --global alias.ds 'diff --staged'
git config --global alias.dsc 'diff --staged --color-words'
git config --global alias.s 'status'
git config --global alias.c 'checkout'
git config --global alias.cb 'checkout -b'
git config --global alias.cd 'checkout --detach'
git config --global alias.a 'add'
git config --global alias.cm 'commit -m'
git config --global alias.ca 'commit --amend'
git config --global alias.p 'push'
git config --global alias.pf 'push -f'
git config --global alias.r 'rebase'
git config --global alias.rc 'rebase --continue'
git config --global alias.ra 'rebase --abort'
git config --global alias.pl 'pull'
git config --global alias.ri 'rebase -i'
git config --global alias.st 'stash'
git config --global alias.sta 'stash apply'
git config --global alias.stl 'stash list'
git config --global alias.stp 'stash pop'
git config --global alias.stpm 'stash push -m'
git config --global alias.rf 'reflog'
git config --global alias.b 'branch'
git config --global alias.bd 'branch -d'
git config --global alias.bl 'blame'
git config --global alias.cl 'config -l'
git config --global alias.rs 'reset HEAD'
git config --global alias.cp 'cherry-pick'
git config --global alias.cpn 'cherry-pick -n'
